minishift/minishift-addons

- CONTRIBUTING.adoc
- README.adoc
- README.md
Fixes issue #1 
This PR includes an introduction to add-ons, to the repository, and basic usage/contribution instructions.
Also includes CONTRIBUTING.adoc file with specific note about submitting new add-ons.
WIP/assumptions/TBD:
1. I assumed the community add-ons would need to be stored under some sub-directory named "add-ons", but if you have some other plan then tell me and I will change the instructions. I recommend keeping the add-ons in a sub-directory rather than in the root of the repository.
2. I assumed that in order to use add-ons from this repository, users will need to download/clone the repo and manually copy the add-ons. If I was mistaken, please propose different workflow.
3. I kept the CI button because every other repo has this, but if there's nothing really to build …
> Issue #1 create initial README content

- add-ons/fabric8/README.md
> Issue #20 Fix RAM size in fabric8 add-on usage guide

- add-ons/fabric8/README.md
Forgot to update disk size as well in https://github.com/minishift/minishift-addons/pull/21.
Needed for consistency.
> Issue #20 Fix disk size in fabric8 add-on guide

- add-ons/cockpit/README.md
- add-ons/cors/README.md
- add-ons/helm/README.md
- add-ons/kube-dashboard/README.md
- add-ons/prometheus/README.md
- add-ons/workshop/README.md
Quick fix for broken links in some addon folders: cockpit, cors etc.
> Issue #33 - Fix broken links in some addon READMEs

- add-ons/cockpit/README.md
- add-ons/cors/README.md
- add-ons/helm/README.md
- add-ons/kube-dashboard/README.md
- add-ons/management-infra/README.md
- add-ons/prometheus/README.md
- add-ons/workshop/README.md
> Issue #37 Fix rendering of headings

- add-ons/prometheus/README.md
Fix #40 
cc @jorgemoralespou 
See https://youtu.be/VpXoD97-YHU
> Issue #40 Update Prometheus add-on README to use admin user to login with

- add-ons/debezium/README.md
- add-ons/debezium/debezium.addon
- add-ons/debezium/register.json
A PR for https://github.com/minishift/minishift-addons/issues/46
> Debezium add-on

- add-ons/che/che.addon
- add-ons/che/che.addon.remove
> Issue #62 Fixing Che for v3.7.0

- add-ons/debezium/debezium.addon
Strimzi is the new kid on the block - Barnabas was renamed, and the 0.1.0 release is used from Strimzi
> Using the latest Strimzi images

- CONTRIBUTING.adoc
Added the required commit message format
Fixes #32 
Signed-off-by: Lalatendu Mohanty <lmohanty@redhat.com>
> Issue #32 Updating the contribution guidelines

- add-ons/che/README.md
> Issue #97 Remove unnecessary add-env flags from che remove command

- Makefile
- README.adoc
- centos_ci.sh
- test/utils/minishift_latest_version.py
Fix #27 
Need this https://github.com/minishift/minishift-ci-jobs/pull/55 to be merged first to test functionally.
> Issue #27 Provide nightly CI job to test minishift add-ons

- add-ons/eap-cd/eap-cd.addon
- add-ons/eap-cd/templates/eap-cd-amq-persistent-s2i.json
- add-ons/eap-cd/templates/eap-cd-amq-s2i.json
- add-ons/eap-cd/templates/eap-cd-basic-s2i.json
- add-ons/eap-cd/templates/eap-cd-https-s2i.json
- add-ons/eap-cd/templates/eap-cd-image-stream.json
- add-ons/eap-cd/templates/eap-cd-mongodb-persistent-s2i.json
- add-ons/eap-cd/templates/eap-cd-mongodb-s2i.json
- add-ons/eap-cd/templates/eap-cd-mysql-persistent-s2i.json
- add-ons/eap-cd/templates/eap-cd-mysql-s2i.json
- add-ons/eap-cd/templates/eap-cd-postgresql-persistent-s2i.json
- add-ons/eap-cd/templates/eap-cd-postgresql-s2i.json
- add-ons/eap-cd/templates/eap-cd-sso-s2i.json
- add-ons/eap-cd/templates/eap-cd-third-party-db-s2i.json
- add-ons/eap-cd/templates/eap-cd-tx-recovery-s2i.json
- test/integration/features/addon-eap-cd.feature
> Issue #117 Add EAP CD imagestreams and templates

- add-ons/fabric8-launcher/README.md
- add-ons/fabric8-launcher/fabric8-launcher.addon
- add-ons/fabric8-launcher/fabric8-launcher.addon.remove
> added fabric8-launcher

- add-ons/che/che.addon.remove
- add-ons/che/templates/che-single-user.yml
Fix #106 and set `CHE_WORKSPACE_AUTO_START` to true
> Issue #106 fix Che remove script

- add-ons/eap-cd/templates/eap-cd-amq-persistent-s2i.json
- add-ons/eap-cd/templates/eap-cd-amq-s2i.json
- add-ons/eap-cd/templates/eap-cd-basic-s2i.json
- add-ons/eap-cd/templates/eap-cd-https-s2i.json
- add-ons/eap-cd/templates/eap-cd-image-stream.json
- add-ons/eap-cd/templates/eap-cd-mongodb-persistent-s2i.json
- add-ons/eap-cd/templates/eap-cd-mongodb-s2i.json
- add-ons/eap-cd/templates/eap-cd-mysql-persistent-s2i.json
- add-ons/eap-cd/templates/eap-cd-mysql-s2i.json
- add-ons/eap-cd/templates/eap-cd-postgresql-persistent-s2i.json
- add-ons/eap-cd/templates/eap-cd-postgresql-s2i.json
- add-ons/eap-cd/templates/eap-cd-sso-s2i.json
- add-ons/eap-cd/templates/eap-cd-third-party-db-s2i.json
- add-ons/eap-cd/templates/eap-cd-tx-recovery-s2i.json
- test/integration/features/addon-eap-cd.feature
Fix https://github.com/minishift/minishift-addons/issues/136.
> Issue #136 Update eap-cd addon for version 13 of EAP-CD

- Gopkg.lock
- Makefile
- test/integration/features/che.feature
Fix https://github.com/minishift/minishift-addons/issues/129.
> Issue #129 Add scenario for removal of Che addon

- README.adoc
- centos_ci.sh
> Update CI to use centos instead of b2d

- CONTRIBUTING.adoc
- README.adoc
- TESTING.adoc
- add-ons/ansible-service-broker/README.md
- add-ons/debezium/README.md
- add-ons/fabric8/README.md
- add-ons/grafana/README.md
- add-ons/htpasswd-identity-provider/README.adoc
- add-ons/htpasswd-identity-provider/htpasswd-identity-provider.addon
- add-ons/htpasswd-identity-provider/htpasswd-identity-provider.addon.remove
- add-ons/istio/README.adoc
> Issue #159 Fix url to reflect OKD rebranding

- add-ons/istio/README.adoc
- corrected confusing addon enablement instruction
- added anyuid and admin-user addon as part of profile setup instruction
> Resolving #167

- add-ons/istio/README.adoc
- Resolving Issue #169
- other minor readme updates
> Removed dynamic-admission-controllers addon

- add-ons/eap-cd/eap-cd.addon
- add-ons/eap-cd/imagestream/eap-cd-image-stream.json
- add-ons/eap-cd/templates/eap-cd-amq-persistent-s2i.json
- add-ons/eap-cd/templates/eap-cd-amq-s2i.json
- add-ons/eap-cd/templates/eap-cd-https-s2i.json
- add-ons/eap-cd/templates/eap-cd-mongodb-persistent-s2i.json
- add-ons/eap-cd/templates/eap-cd-mongodb-s2i.json
- add-ons/eap-cd/templates/eap-cd-mysql-persistent-s2i.json
- add-ons/eap-cd/templates/eap-cd-mysql-s2i.json
- add-ons/eap-cd/templates/eap-cd-postgresql-persistent-s2i.json
- add-ons/eap-cd/templates/eap-cd-postgresql-s2i.json
- add-ons/eap-cd/templates/eap-cd-sso-s2i.json
- add-ons/eap-cd/templates/eap-cd-starter-s2i.json
- add-ons/eap-cd/templates/eap-cd-third-party-db-s2i.json
- add-ons/eap-cd/templates/eap-cd-tx-recovery-s2i.json
- centos_ci.sh
- test/integration/features/addon-eap-cd.feature
> Issue #176 Update eap-cd addon for EAP-CD-14

- add-ons/eap-cd/eap-cd.addon
- add-ons/eap-cd/imagestream/eap-cd-image-stream.json
- add-ons/eap-cd/templates/eap-cd-amq-persistent-s2i.json
- add-ons/eap-cd/templates/eap-cd-amq-s2i.json
- add-ons/eap-cd/templates/eap-cd-basic-s2i.json
- add-ons/eap-cd/templates/eap-cd-https-s2i.json
- add-ons/eap-cd/templates/eap-cd-mongodb-persistent-s2i.json
- add-ons/eap-cd/templates/eap-cd-mongodb-s2i.json
- add-ons/eap-cd/templates/eap-cd-mysql-s2i.json
- add-ons/eap-cd/templates/eap-cd-postgresql-persistent-s2i.json
- add-ons/eap-cd/templates/eap-cd-postgresql-s2i.json
- add-ons/eap-cd/templates/eap-cd-sso-s2i.json
- add-ons/eap-cd/templates/eap-cd-starter-s2i.json
- add-ons/eap-cd/templates/eap-cd-third-party-db-s2i.json
- add-ons/eap-cd/templates/eap-cd-tx-recovery-postgresql-s2i.json
- add-ons/eap-cd/templates/eap-cd-tx-recovery-s2i.json
- test/integration/features/addon-eap-cd.feature
>  Issue #179 Update eap-cd addon to EAP-CD-15
